#include <iostream>
#include <exception>
#include "./include/local_main.hpp"
#include "./include/Data_Types/Value/Value.hpp"

int main(int argc, char** argv) {
	try {
		
	} catch (const std::exception& err) {

	}
}